# Generated by Buildr 1.3.5, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "sequence"
COPYRIGHT = ""

require 'buildr/scala'

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

task :run => ["sequence:run"]

desc "The Sequence project"
define "sequence" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  task :run => :compile do
    Java::Commands.java('sequence.Sequence', :classpath => compile.dependencies + [compile.target.to_s])
  end
  manifest["Implementation-Vendor"] = COPYRIGHT
end
